### PR TITLE
Fix: problem caused by `strict`

### LINKED ISSUE #387: [Bug] Log in Button is not working
As title said, the Login button have no response except for sfx under complex condition.
The only method I can login is downgrade to 0.6.2 and upgrade to 0.6.3 .

(In video, I turn off BGM, the button sfx is working)

---

**Normal Version:** v0.6.2
**Bug Version:** v0.6.3, v0.6.3-pre1
**Platform**: Android arm64-v8a and Linux x86_64 (self-built)

---

#### Reproduce Method
1. Remove data/ folder if you are not a new phira
2. Open Phira
3. Login once (input email and password or not)
4. "Next page" multiple times and Accept
5. Restart Phira
6. Log out if you login already
7. Login and you will found that you click the button but not working

> For any normal player, just log out, and try to login back, the bug will happen

https://github.com/user-attachments/assets/d5c5d16a-e46c-42b2-8c2b-f691190ae113

### PR DESCRIPTION
**Pull request by liquidhelium**
Please test before merge
May fix #387

### CODE REVIEW

**Comment by YuevUwU** [comment]
**Test Platform:** Linux Mint 21.2
**Current Behavior:**
1. Profile Button: load tos
2. Login Button: TOS Acception
3. Re-login without exit: TOS Acception without loading
4. Logout and exit the game
5. Profile Button: not load tos
6. Login Button: load tos **but not enter TOS Acception**
7. Login Button **(again)**: TOS Acception

Seems that 6 and 7 can be enhanced.
1 and 2 is different but tolerable...
But indeed they depend on what the main Dev thinks.

**Comment by liquidhelium** [comment]
I've added a 10s delay when loading tos, for debugging purpose.
It will try load term at startup(without loading screen),
and show loading screen for this load if it hasn't completed.
As for 6 and 7, I'll fix it in the evening(GMT+8)

**Comment by liquidhelium** [comment]
New behaviour:
Won't load terms at startup.
  - Instead, load when login button was pressed.
  - In the library page, load when required.

Show a loading screen with infomation when loading terms.
Show dialog right after loaded. If encountered any error in the loading process, show error dialog.

**Comment by Guo2010tw** [comment]
How to download the updated version?

**Comment by YuevUwU** [comment]
[Enhancement]
When the server is unable to fetch tos, Loading will fall into a fetch loop, even if Error has popped up. 
(But now that the server is about to stabilize, it may be difficult to debug)

Another point is that Loading does not have a cancel button (as is the practice of downloading online charts). 
The reason for recommend is that we have removed the 10s client timeout threshold, resulting in the user being unable to exit this LoadingView to play offline chart if the server has not responded for a long time, and can only restart the game. 
(I also tried pressing a blank space but it didn't work)

I apologize that I caused you trouble in your busy schedule😓

**Comment by liquidhelium** [comment]
Acturally it would be considered a error if terms are not loaded after a long time, which is a feature of every connection in phira.

**Review by NuanRMxi — APPROVED** [review]

**Pull request merged**
